package com.localmath.engine

/**
 * What to plot next to a solution. Curves are JavaScript expressions in x generated by the engine
 * (never user text), drawn by the page in MathView.
 */
data class Curve(val js: String, val label: String, val verticalX: Double? = null)

data class GraphPoint(val x: Double, val y: Double, val label: String)

/** Part of the x-axis to highlight (inequalities). Infinite ends use ±Infinity. */
data class XInterval(val from: Double, val to: Double, val closedFrom: Boolean, val closedTo: Boolean)

data class Graph(
    val curves: List<Curve>,
    val points: List<GraphPoint> = emptyList(),
    val shadeFrom: Double? = null,       // shade under curves[0] between these x values
    val shadeTo: Double? = null,
    val intervals: List<XInterval> = emptyList(),
    val xMin: Double = -8.0,
    val xMax: Double = 8.0
)

object Graphs {

    /** A curve y = s(v), or null if s uses other variables or can't be drawn. */
    fun curve(s: S, v: Char, label: String? = null): Curve? {
        if (!Sym.variables(s).all { it == v }) return null
        return Curve(toJs(s, v), label ?: "y = ${Sym.latex(s, v)}")
    }

    fun curveOf(e: Expr, v: Char): Curve? = try { curve(Sym.from(e), v) } catch (_: MathError) { null }

    /** x-window that shows every interesting x (roots, limits …) with some room around them. */
    fun window(focus: List<Double>): Pair<Double, Double> {
        val xs = focus.filter { it.isFinite() }
        if (xs.isEmpty()) return -8.0 to 8.0
        val lo = xs.min()
        val hi = xs.max()
        val pad = Math.max(3.0, (hi - lo) * 0.4)
        return (lo - pad) to (hi + pad)
    }

    fun build(
        curves: List<Curve?>,
        points: List<GraphPoint> = emptyList(),
        focus: List<Double> = emptyList(),
        shade: Pair<Double, Double>? = null,
        intervals: List<XInterval> = emptyList()
    ): Graph? {
        val cs = curves.filterNotNull()
        if (cs.isEmpty() && points.isEmpty()) return null
        val (lo, hi) = window(focus + points.map { it.x } + listOfNotNull(shade?.first, shade?.second) +
            intervals.flatMap { listOf(it.from, it.to) })
        return Graph(cs, points.filter { it.x.isFinite() && it.y.isFinite() }, shade?.first, shade?.second, intervals, lo, hi)
    }

    fun label(x: Double, y: Double) = "(${short(x)}, ${short(y)})"

    fun short(d: Double): String {
        if (Math.abs(d) < 1e-9) return "0"
        val r = Math.round(d * 1000) / 1000.0
        return if (r == Math.rint(r)) r.toLong().toString() else r.toString()
    }

    // ---------------- S -> JavaScript ----------------

    fun toJs(s: S, v: Char): String = when (s) {
        is S.Num -> "(${s.v.num}/${s.v.den})"
        is S.Var -> if (s.name == v) "x" else "NaN"
        is S.Const -> if (s.name == 'π') "Math.PI" else "Math.E"
        is S.Func -> {
            val a = toJs(s.arg, v)
            when (s.name) {
                "sin" -> "Math.sin($a)"
                "cos" -> "Math.cos($a)"
                "tan" -> "Math.tan($a)"
                "ln" -> "ln($a)"
                "log" -> "lg($a)"
                "abs" -> "Math.abs($a)"
                "arcsin" -> "Math.asin($a)"
                "arccos" -> "Math.acos($a)"
                "arctan" -> "Math.atan($a)"
                "sinh" -> "Math.sinh($a)"
                "cosh" -> "Math.cosh($a)"
                "tanh" -> "Math.tanh($a)"
                "arsinh" -> "Math.asinh($a)"
                "arcosh" -> "Math.acosh($a)"
                "artanh" -> "Math.atanh($a)"
                else -> "NaN"
            }
        }
        is S.Pow -> "pw(${toJs(s.base, v)}, ${toJs(s.exp, v)})"
        is S.Sum -> s.terms.joinToString(" + ", "(", ")") { toJs(it, v) }
        is S.Prod -> s.factors.joinToString(" * ", "(", ")") { toJs(it, v) }
    }
}
